version: '3.5'
services:
  angular:
    container_name: angular_container
    build: ./
    volumes:
      - solr_cores_prod:/var/solr/data/
    ports:
      - '80:80'
    command: bash -c "echo 'daemon off;' >> /etc/nginx/nginx.conf && rm /etc/nginx/sites-enabled/default && ng build && cp /etc/nginx/sites-available/app.prod.conf /etc/nginx/sites-enabled/ && nginx"


  solr:
    container_name: apache_solr
    image: solr:8.3.0
volumes:
  solr_cores_prod: