version: '3.5'
services:
  angular:
    container_name: angular_container
    build: ./
    volumes:
      - './app:/usr/src/app'
      - solr_cores_dev:/var/solr/data/
    ports:
      - '8080:80'
    command: bash -c "rm /etc/nginx/sites-enabled/default && cp /etc/nginx/sites-available/app.dev.conf /etc/nginx/sites-enabled/ && service nginx restart && npm install && ng serve --public-host http://localhost --port 4200"

  solr:
    container_name: apache_solr
    image: solr:8.3.0
volumes:
  solr_cores_dev: