version: '3.5'
services:
  angular:
    ports:
      - '80:8080'
    command: bash -c "echo 'daemon off;' >> /etc/nginx/nginx.conf && rm /etc/nginx/sites-enabled/default && ng build && cp /etc/nginx/sites-available/app.prod.conf /etc/nginx/sites-enabled/ && nginx"
  solr:
    volumes:
      - solr_cores_prod:/var/solr/data/
volumes:
  solr_cores_prod: